# Generated by Django 5.2.6 on 2025-09-14 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='work_experience',
            new_name='experience',
        ),
    ]
